server {
    listen 80;
    server_name gym.remotepcsolutions.com; # Aquí pondrás tu dominio o IP pública después
    client_max_body_size 100M; # Permitir subir videos pesados

    # Redirigir el tráfico del Backend (NestJS)
    location /api/ {
        proxy_pass http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Servir archivos estáticos subidos (Fotos/Videos de máquinas)
    location /uploads/ {
        alias /app/uploads/;
        access_log off;
        expires 30d;
    }

    # Redirigir el resto del tráfico al Frontend (Next.js)
    location / {
        proxy_pass http://frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}