name: Deploy Gym TechnoFit to AWS

on:
  push:
    branches:
      - main # Se ejecuta solo cuando haces push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/ubuntu/gym-technofit
            git pull origin main
            
            # 1. Apagamos y limpiamos los contenedores actuales para evitar el bug de ContainerConfig
            docker-compose down
            
            # Limpieza forzada de bloqueos de Chromium para evitar colisiones de sesión en WhatsApp Web
            sudo find ./backend/.wwebjs_auth -name 'Singleton*' -delete || true
            
            # 2. Reconstruimos y levantamos en limpio
            docker-compose up -d --build